channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  - python=3.10.12                    # https://pyreadiness.org/3.10
  - pip=23.2.1                        # https://pip.pypa.io/en/stable/news
  - pip:
    - rpaframework==27.6.0            # https://rpaframework.org/releasenotes.html
