channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.9.13
  - pip=20.1
  - pip:
      # Define pip packages here.
      # https://pypi.org/

      # https://rpaframework.org/releasenotes.html
      - rpaframework==15.4.0
